#!/bin/bash
XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-/run/user/1000}
WAYLAND_SOCK="${XDG_RUNTIME_DIR}/wayland-0"

set -e

GUEST="$1"
shift
mkdir -p "./Home/$GUEST"
chmod 777 "./Home/$GUEST"

# 1. Get Host GIDs
VIDEO_GID=$(getent group video | cut -d: -f3)
RENDER_GID=$(getent group render | cut -d: -f3)

setfacl -m u:100999:rw "${WAYLAND_SOCK}"

docker run -it --rm \
  --user 0:0 \
  --security-opt seccomp=unconfined \
  --device /dev/dri:/dev/dri \
  --group-add "$VIDEO_GID" \
  --group-add "$RENDER_GID" \
  -v "${WAYLAND_SOCK}":/run/user/1000/wayland-0:rw \
  -v "${WAYLAND_SOCK}":/run/user/0/wayland-0:rw \
  -v "./Home/$GUEST/user":/home/user \
  -v "./Home/$GUEST/root":/root \
  wayland-hook:$GUEST \
  dbus-run-session $@

