ARG BASE
FROM $BASE

RUN apt-get update && apt-get install -y wget gpg ca-certificates --no-install-recommends

RUN wget -4 -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /usr/share/keyrings/packages.microsoft.gpg && \
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" \
        > /etc/apt/sources.list.d/vscode.list

RUN apt-get update && apt-get install -y code --no-install-recommends

RUN apt-get clean && rm -rf /var/lib/apt/lists/*
